package com.crisol.ahorrandome.exception;

public enum ErrorType {
    USER_NOT_FOUND,
    VALIDATION_ERROR,
    AUTHENTICATION_FAILED,
    DATABASE_ERROR,
    TRANSACTION_FAILURE,
    GENERIC_ERROR,
    ACCESS_DENIED,
    RESOURCE_CONFLICT,
    BAD_REQUEST,
    UNKNOWN_ERROR,
    NOT_FOUND,
    UNAUTHORIZED,
    FORBIDDEN,
    SERVICE_UNAVAILABLE,
    TIMEOUT,
    RATE_LIMIT_EXCEEDED,
    INVALID_INPUT,
    OPERATION_NOT_SUPPORTED,
    DATA_INTEGRITY_VIOLATION,
    DATA_NOT_FOUND,
    DATA_ALREADY_EXISTS,
    UNEXPECTED_ERROR,   
    INVALID_CREDENTIALS,
    INSUFFICIENT_PERMISSIONS,
    EXTERNAL_SERVICE_FAILURE;
}
